// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/embedding-connections/Attention.tsx": () => import("../components/mockups/embedding-connections/Attention.tsx"),
  "./components/mockups/embedding-connections/Current.tsx": () => import("../components/mockups/embedding-connections/Current.tsx"),
  "./components/mockups/embedding-connections/KnnWeb.tsx": () => import("../components/mockups/embedding-connections/KnnWeb.tsx"),
  "./components/mockups/embedding-connections/ProximityFog.tsx": () => import("../components/mockups/embedding-connections/ProximityFog.tsx")
};
